### PR TITLE
pubcrawl: Add mentioned users to 'cc' for public posts

### PR DESCRIPTION
**Pull request by jschweinsberg**
Mastodon users didn't get notifications for @-mentions.

To get notifications, mentioned users need to be explicitly listed to be part of the audience inside the activitypub payload.

This change adds mentioned users to 'cc' for public posts.

### CODE REVIEW

**Comment by jschweinsberg** [comment]
One additional idea:

When I post a private post (not a reply) and I give Bob and Alice (both activitypub connections) permission to view the post. But mentioning Alice and _Mike_ inside the post. Wouldn't it be correct to add Alice to 'cc'?

Mike never sees the message, Bob sees the message and Alice sees the message and gets a notification. (The intersection of mentioned users and users with permissions to see the post)

That's only an idea and currently it seems that it wouldn't work for private notes. (because of Mastodon and handling private posts? I'm not 100% sure)

**Comment by zotlabs** [comment]
The one thing to keep in mind is that in Hubzilla, (normal) mentions aren't allowed to change the distribution of a post. The activitypub addressing fields provide the distribution instructions for that network. So if Alice is mentioned in a public post, we need to add Alice specifically to the delivery list in order for Mastodon to notify her. That's fine. In a private post, she should already be on the delivery list that her server receives so we shouldn't have to add it if she's mentioned.  We shouldn't need to add Alice on Bob's copy of the private message because Bob's server isn't going to be providing mention notifications for Alice. 

Mike should never get the message or show up in the delivery list. 

Anyway that's how it should work in my opinion. If we're doing something different we may need to correct it. I haven't yet looked to make sure that is in fact what we do before posting this. We may have gotten it wrong. 

I'm not too concerned about how Mastodon does this as long as they deliver the private notes as requested. (One to Alice with only Alice in the delivery list and one to Bob with only Bob in the delivery list - **even if** it is the same message-id and delivered to the same server). 

This is where there is most likely to be a difference of opinion between the two implementations. We *may* need to include all the recipients for a given server on all copies delivered to that server to make it work correctly for other projects and implementations. I would be OK with this because that's how zot works under the covers. Zot only delivers one copy of a given message to a given server and the recipient list contains everybody *on that server* that should receive it. 

I would have to look but I'm hoping I didn't code it so the entire private ACL is included in every ActivityPub message. That's the way AP was originally intended to work. If I actually did do that I wasn't thinking straight at the time. If Mastodon does this and relies on it, I'm not certain we can resolve our differences.

**Comment by jschweinsberg** [comment]
It only addresses the public posts, so it should be fine to be merged.
No more additional changes.

**Comment by jschweinsberg** [comment]
The merge reverted some part of Mikes changes regarding bcc and bto

**Pull request merged**
